# config_gpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-standard-8
      acceleratorType: NVIDIA_TESLA_K80
      acceleratorCount: 1
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/spherical-park-374308/landscape_training_cpu
      env: 
      - name: WANDB_API_KEY
        value: <key-as-string>