model:
  backbone: resnet18 #Options: resnet18, resnet34, resnet50, etc..
  pretrained: True #Options: True, False

data:
  location: data #Location of data folder
  augmentation: null # Options 
  batch_size: 32
  input_size: 224
  classes: ['Coast', 'Desert', 'Forest', 'Glacier', 'Mountain']

hyperparameters:
  learning_rate: 0.007 #1e-4 #learning rate
  weight_decay: 1e-5
  sweep_config: "" #"config/sweep_config.yaml"

training:
  epochs: 30
  optimizer: sgd #Options adam, adamW, ...
  scheduler: multisteplr #Options: StepLR, MultiStepLR
  step: 20
  early_stop: False #Whether to implement early stop in case lr is not increasing
  val_interval: 1
  loss_fun: "cross_entropy"

reproducability:
  apply: True
  seed: 19 #19 for team19

wandb: 
  project: backbones
  entity: dtumlops-group19
  